### ISSUE TITLE
Does not work on Jekyll 3.4.0

### ISSUE THREAD

**Issue by anatoliykmetyuk** [bwillis/jekyll-github-sample#8]
When trying to run the sample from the main page on Jekyll 3.4.0:

```
{% github_sample_ref /bwillis/versioncake/989237901cb873f96df12be48cbf1239be496bd7/Appraisals %}
{% highlight ruby %}
{% github_sample /bwillis/versioncake/989237901cb873f96df12be48cbf1239be496bd7/Appraisals 0 5 %}
{% endhighlight %}
```

It gives:

```
  Liquid Exception: bad value for range in /Users/anatolii/Projects/blog/src/_posts/2017-02-23-test-plugins.md
/Library/Ruby/Gems/2.0.0/gems/jekyll_github_sample-0.3.0/lib/jekyll_github_sample/code_tag.rb:25:in `render': bad value for range (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/tags/highlight.rb:32:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:134:in `render_liquid'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:82:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:452:in `block (2 levels) in render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:450:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:450:in `block in render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:449:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:449:in `render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:190:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:69:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/command.rb:26:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

The same project works on Jekyll 2.4.0.

**Comment by anatoliykmetyuk** [comment]
The same happens with 3.0.0 too.

**Comment by chrislovecnm** [comment]
Bump, any update?
